### ISSUE TITLE
Font dropdowns are not sorted alphabetically.

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#1]
In the Amigo settings, the font dropdowns do not sort the font names alphabetically...

![image](https://user-images.githubusercontent.com/700064/86332483-7e3cd200-bc42-11ea-99ac-1f13b36a5af5.png)

This affects the font dropdown on the `Defaults` and `Custom Styles` panels.

**Comment by omsharp** [comment]
Hi Jason,

This issue and also issue #3 should be solved in v0.2 (available now).

Thanks for the feedback.
