### ISSUE TITLE
Last letter of classification is displayed in Bookmarks List accidentally.

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#12]
Version 0.8.1

Given the following classification...

![image](https://user-images.githubusercontent.com/700064/87281208-e4e7a880-c4ea-11ea-9150-f6802ff19958.png)

When I use this and look at the Bookmarks List, I noticed that the latter 'g' is shown at the start of the line, like this...

![image](https://user-images.githubusercontent.com/700064/87281293-fa5cd280-c4ea-11ea-9e9f-ec8defac79a3.png)

It might be something to do with the casing of the classification. I see that all uppercase classifications are affected by this issue, but lowercase classification are not...

![image](https://user-images.githubusercontent.com/700064/87281658-5c1d3c80-c4eb-11ea-9738-4d73c9199b73.png)

**Comment by omsharp** [comment]
I think this should be solved in v0.8.2

**Comment by MrClyfar** [comment]
In version 0.8.2 this issue looks to have been resolved.
