### ISSUE TITLE
Bookmarks List is empty when it should be showing a token from a file

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#2]
I have a classification named `Compress` and I have used it in a .cs file like this...

![image](https://user-images.githubusercontent.com/700064/86333070-51d58580-bc43-11ea-8f7d-d45d86b51ac8.png)

As you can see, it does not appear in the bookmarks list. I pressed the refresh button on the list, but it still did not show Compress.

**Comment by omsharp** [comment]
Please check v0.3 and see if it solves some of the issues.

**Comment by omsharp** [comment]
@MrClyfar 
Please check v0.3 and see if it solves some of the issues.

**Comment by omsharp** [comment]
@MrClyfar 
Can you please confirm what issues solved by v0.3, and close them.
Thanks.

**Comment by omsharp** [comment]
@MrClyfar 
Is this still a problem?

**Comment by MrClyfar** [comment]
Tested this in version 0.5, all looking good now.
