### ISSUE TITLE
Comment font colour does not change after editing custom style.

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#4]
I have a custom style named `Signpost`. When I first created it, I set  the foreground colour to a shade of purple. When typing out comments which use the `Signpost` style, they appeared in the correct colour.

When I change the foreground colour of that custom style, the classification font colour changes, but not the comment text. For example, I changed the foreground colour to red...

![image](https://user-images.githubusercontent.com/700064/86335161-0a9cc400-bc46-11ea-98ef-7f7e3c747a0f.png)

and the comment was displayed like this...

![image](https://user-images.githubusercontent.com/700064/86335196-18eae000-bc46-11ea-958d-06e6e7dede46.png)

The comment text is still displayed in purple. I was expecting the text to be red to match the classification font colour.

I typed out the comment on a new line, from scratch, just to check whether it was an issue with existing comments. But, even when typing a new comment, the classification was in red, but the comment text was purple.

**Comment by MrClyfar** [comment]
I just tried this in version 0.4, and it looks to have been fixed.

**Comment by MrClyfar** [comment]
Just found this issue in version 0.5.

Apologies, I may have mistakenly thought this was fixed in 0.3/0.4

I have a classification which was coloured pink. I changed it to be green. When using this classification, the main comment text is still coloured pink.

![image](https://user-images.githubusercontent.com/700064/86779489-8a1a0100-c053-11ea-80cd-03478035f8a7.png)

**Comment by omsharp** [comment]
I can't reproduce this issue.

**Comment by MrClyfar** [comment]
Testing version 0.8.1 it looks as though this issue has been fixed.
