### ISSUE TITLE
New classification does not appear in Bookmarks List

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#8]
**Version 0.3**

I added a new classification called `buga`.

I then added a comment onto a source code line using this new classification

`//buga This is a test`

The Bookmarks List did not pick up this new classification. It does not appear in the classification list either, only the classifications that were there before I added `buga` appear in the list. Even after I press the refresh button.

![image](https://user-images.githubusercontent.com/700064/86570510-ef90c380-bf67-11ea-85e3-d3be9fdac065.png)

![image](https://user-images.githubusercontent.com/700064/86570529-f7506800-bf67-11ea-8d7c-e55622e83c09.png)

**Comment by omsharp** [comment]
Solved in v0.4
