### ISSUE TITLE
Deleting multiple lines which contain classification tokens causes Visual Studio to crash.

### ISSUE THREAD

**Issue by MrClyfar** [omsharp/docomment-progress#9]
Version 0.4

When deleting more than one line of comments which contain a classification token, Visual Studio crashes.

when I delete a single line at a time, all is fine. But when I delete two or more, that is when the crash happens.

Here is a gif which demos what happens...

In this demo, I highlight all of the comment lines then I press the `Delete` key. Visual Studio will display the crashed dialog window...

![Crash When Deleting Multiple Classification Comments](https://user-images.githubusercontent.com/700064/86626204-488b4680-bfbe-11ea-8ba1-fe3ca1b823af.gif)

**Comment by omsharp** [comment]
Yes, actually I found this bug myself yesterday. I'm working on it.

**Comment by omsharp** [comment]
@MrClyfar 
Ok, it should be solved in v0.5
